### ISSUE TITLE
Post title metadata string literal should be double-quoted

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/blog#5]
To go with the whole idea of "double quotes is for things that are read by humans; single quotes for everything else".

Correct example:

```yaml
title: "Rewrote it Again"
permalink: '3-rewrote-it-again'
date: {m: 4, d: 14, y: 2017}
categories:
- 'text'
- 'blog-dev'
```

Note the title entry is double-quoted while the permalink and categories aren't.
